# Review Problems

**1)    Define the following metrics and perform the following operations**

Matrix A =  [[ 3.7827  3.3454  3.2341]  , [ 2.2122  3.5678  3.9087] ,
[1.1234  2.8934,  5.9087]].

Matrix B =  [[ 3.1234  3.0987  3.1234]  , [ 2.1111  3.2222  3.3333] ,
[1.0987  1.3456,  5.1234]].

Matrix C =  [[ 3.1243  3.0989  3.1256 ]  , [ 2.6721  3.6785  3.9017] ,
[1.1254  2.8956,  5.9187]].

**i)    Write a Python program using Python Lists**

In [7]:
import time

# Define matrices
A = [[3.7827, 3.3454, 3.2341], [2.2122, 3.5678, 3.9087], [1.1234, 2.8934, 5.9087]]
B = [[3.1234, 3.0987, 3.1234], [2.1111, 3.2222, 3.3333], [1.0987, 1.3456, 5.1234]]
C = [[3.1243, 3.0989, 3.1256], [2.6721, 3.6785, 3.9017], [1.1254, 2.8956, 5.9187]]

# Print matrices
print("Matrix A:")
for row in A:
    print(row)

print("\nMatrix B:")
for row in B:
    print(row)

print("\nMatrix C:")
for row in C:
    print(row)

# Matrix addition
def add_matrices(A, B):
    return [[A[i][j] + B[i][j] for j in range(len(A[0]))] for i in range(len(A))]

# Matrix subtraction
def subtract_matrices(A, B):
    return [[A[i][j] - B[i][j] for j in range(len(A[0]))] for i in range(len(A))]

# Element-wise multiplication
def elementwise_multiply_matrices(A, B):
    return [[A[i][j] * B[i][j] for j in range(len(A[0]))] for i in range(len(A))]

# Matrix multiplication (dot product)
def matrix_multiply(A, B):
    result = [[0] * len(B[0]) for _ in range(len(A))]
    for i in range(len(A)):
        for j in range(len(B[0])):
            for k in range(len(B)):
                result[i][j] += A[i][k] * B[k][j]
    return result

# Profiling
start_time = time.time()
print("\nMatrix A + B:", add_matrices(A, B))
print("Matrix A - B:", subtract_matrices(A, B))
print("Element-wise multiplication of A and B:", elementwise_multiply_matrices(A, B))
print("Matrix multiplication of A and B:", matrix_multiply(A, B))
end_time = time.time()

print(f"\nTime taken using Python lists: {end_time - start_time} seconds")


Matrix A:
[3.7827, 3.3454, 3.2341]
[2.2122, 3.5678, 3.9087]
[1.1234, 2.8934, 5.9087]

Matrix B:
[3.1234, 3.0987, 3.1234]
[2.1111, 3.2222, 3.3333]
[1.0987, 1.3456, 5.1234]

Matrix C:
[3.1243, 3.0989, 3.1256]
[2.6721, 3.6785, 3.9017]
[1.1254, 2.8956, 5.9187]

Matrix A + B: [[6.9061, 6.444100000000001, 6.3575], [4.3233, 6.79, 7.242], [2.2221, 4.239, 11.0321]]
Matrix A - B: [[0.6593, 0.24670000000000014, 0.11070000000000002], [0.10110000000000019, 0.34560000000000013, 0.5754000000000001], [0.024699999999999944, 1.5478000000000003, 0.7852999999999994]]
Element-wise multiplication of A and B: [[11.814885180000001, 10.36639098, 10.10138794], [4.6701754200000005, 11.49616516, 13.02886971], [1.23427958, 3.89335904, 30.27263358]]
Matrix multiplication of A and B: [[22.43066479, 26.85280533, 39.53569494], [18.736056750000003, 23.61065602, 38.8279668], [16.108972989999998, 20.754939779999997, 43.42603136]]

Time taken using Python lists: 0.0012106895446777344 seconds


**ii)   Write a Python program and NumPy**

In [9]:
import numpy as np
import time

# Define matrices
A = np.array([[3.7827, 3.3454, 3.2341], [2.2122, 3.5678, 3.9087], [1.1234, 2.8934, 5.9087]])
B = np.array([[3.1234, 3.0987, 3.1234], [2.1111, 3.2222, 3.3333], [1.0987, 1.3456, 5.1234]])
C = np.array([[3.1243, 3.0989, 3.1256], [2.6721, 3.6785, 3.9017], [1.1254, 2.8956, 5.9187]])

# Print matrices
print("Matrix A:")
print(A)

print("\nMatrix B:")
print(B)

print("\nMatrix C:")
print(C)

# Matrix addition
def matrix_addition(A, B):
    return A + B

# Matrix subtraction
def matrix_subtraction(A, B):
    return A - B

# Element-wise multiplication
def elementwise_multiplication(A, B):
    return A * B

# Matrix multiplication (dot product)
def matrix_multiplication(A, B):
    return np.dot(A, B)

# Profiling
start_time = time.time()
print("\nMatrix A + B:\n", matrix_addition(A, B))
print("Matrix A - B:\n", matrix_subtraction(A, B))
print("Element-wise multiplication of A and B:\n", elementwise_multiplication(A, B))
print("Matrix multiplication of A and B:\n", matrix_multiplication(A, B))
end_time = time.time()

print(f"\nTime taken using NumPy: {end_time - start_time} seconds")


Matrix A:
[[3.7827 3.3454 3.2341]
 [2.2122 3.5678 3.9087]
 [1.1234 2.8934 5.9087]]

Matrix B:
[[3.1234 3.0987 3.1234]
 [2.1111 3.2222 3.3333]
 [1.0987 1.3456 5.1234]]

Matrix C:
[[3.1243 3.0989 3.1256]
 [2.6721 3.6785 3.9017]
 [1.1254 2.8956 5.9187]]

Matrix A + B:
 [[ 6.9061  6.4441  6.3575]
 [ 4.3233  6.79    7.242 ]
 [ 2.2221  4.239  11.0321]]
Matrix A - B:
 [[0.6593 0.2467 0.1107]
 [0.1011 0.3456 0.5754]
 [0.0247 1.5478 0.7853]]
Element-wise multiplication of A and B:
 [[11.81488518 10.36639098 10.10138794]
 [ 4.67017542 11.49616516 13.02886971]
 [ 1.23427958  3.89335904 30.27263358]]
Matrix multiplication of A and B:
 [[22.43066479 26.85280533 39.53569494]
 [18.73605675 23.61065602 38.8279668 ]
 [16.10897299 20.75493978 43.42603136]]

Time taken using NumPy: 0.012526750564575195 seconds


**2)    Write a Python Program and perform the following operations.**

I.  Create a List {1225, 4986, 6789, 7890, 2345, 6783, 0987, 1234, 8765, 3456}


II. Iterate using a for loop


III.    Iterate using for loop and range


IV. List Comprehension


V.  Enumerate


VI. Iter function and next function


VII.    Map function


VIII.   Using zip


IX. Using NumPy Module

In [21]:
import numpy as np
import timeit

# Define the list
my_list = [1225, 4986, 6789, 7890, 2345, 6783, 987, 1234, 8765, 3456]

# I. Create a List
def create_list():
    return [1225, 4986, 6789, 7890, 2345, 6783, 987, 1234, 8765, 3456]

# II. Iterate using a for loop
def iterate_for_loop(lst):
    result = []
    for item in lst:
        result.append(item)  # Just append the item as it is
    return result

# III. Iterate using for loop and range
def iterate_for_loop_range(lst):
    result = []
    for i in range(len(lst)):
        result.append(lst[i])  # Just append the item as it is
    return result

# IV. List Comprehension
def list_comprehension(lst):
    return [x for x in lst]  # Just include the item as it is

# V. Enumerate
def enumerate_example(lst):
    return list(enumerate(lst))

# VI. Iter function and next function
def iter_next_example(lst):
    iterator = iter(lst)
    result = []
    while True:
        try:
            result.append(next(iterator))  # Append the item as it is
        except StopIteration:
            break
    return result

# VII. Map function
def map_function(lst):
    return list(map(lambda x: x, lst))  # Identity function (no change)

# VIII. Using zip
def zip_example(lst):
    another_list = [10, 20, 30, 40, 50, 60, 70, 80, 90, 100]
    return list(zip(lst, another_list))

# IX. Using NumPy Module
def numpy_example(lst):
    np_array = np.array(lst)
    return list(np_array)  # Just convert to a NumPy array and back to list

# Function to profile operations using timeit
def profile_operations():
    # Timing each operation and printing results
    def time_and_print(func, *args, **kwargs):
        start_time = timeit.default_timer()
        result = func(*args, **kwargs)
        end_time = timeit.default_timer()
        elapsed = end_time - start_time
        return result, elapsed
    
    # I. Create a List
    result, time_create_list = time_and_print(create_list)
    print("I. Create a List:")
    print(result)
    print(f"Time: {time_create_list:.6f} seconds")
    
    # II. Iterating using a for loop
    result, time_for_loop = time_and_print(iterate_for_loop, my_list)
    print("\nII. Iterating using a for loop:")
    print(result)
    print(f"Time: {time_for_loop:.6f} seconds")
    
    # III. Iterating using for loop and range
    result, time_for_loop_range = time_and_print(iterate_for_loop_range, my_list)
    print("\nIII. Iterating using for loop and range:")
    print(result)
    print(f"Time: {time_for_loop_range:.6f} seconds")
    
    # IV. List Comprehension
    result, time_list_comprehension = time_and_print(list_comprehension, my_list)
    print("\nIV. List Comprehension:")
    print(result)
    print(f"Time: {time_list_comprehension:.6f} seconds")
    
    # V. Enumerate
    result, time_enumerate = time_and_print(enumerate_example, my_list)
    print("\nV. Enumerate:")
    print(result)
    print(f"Time: {time_enumerate:.6f} seconds")
    
    # VI. Iter function and next function
    result, time_iter_next = time_and_print(iter_next_example, my_list)
    print("\nVI. Iter function and next function:")
    print(result)
    print(f"Time: {time_iter_next:.6f} seconds")
    
    # VII. Map function
    result, time_map_function = time_and_print(map_function, my_list)
    print("\nVII. Map function:")
    print(result)
    print(f"Time: {time_map_function:.6f} seconds")
    
    # VIII. Using zip
    result, time_zip_example = time_and_print(zip_example, my_list)
    print("\nVIII. Using zip:")
    print(result)
    print(f"Time: {time_zip_example:.6f} seconds")
    
    # IX. Using NumPy Module
    result, time_numpy_example = time_and_print(numpy_example, my_list)
    print("\nIX. Using NumPy Module:")
    print(result)
    print(f"Time: {time_numpy_example:.6f} seconds")

# Main function to demonstrate all operations and profiling
def main():
    # Profile the operations
    profile_operations()

if __name__ == "__main__":
    main()


I. Create a List:
[1225, 4986, 6789, 7890, 2345, 6783, 987, 1234, 8765, 3456]
Time: 0.000007 seconds

II. Iterating using a for loop:
[1225, 4986, 6789, 7890, 2345, 6783, 987, 1234, 8765, 3456]
Time: 0.000010 seconds

III. Iterating using for loop and range:
[1225, 4986, 6789, 7890, 2345, 6783, 987, 1234, 8765, 3456]
Time: 0.000009 seconds

IV. List Comprehension:
[1225, 4986, 6789, 7890, 2345, 6783, 987, 1234, 8765, 3456]
Time: 0.000002 seconds

V. Enumerate:
[(0, 1225), (1, 4986), (2, 6789), (3, 7890), (4, 2345), (5, 6783), (6, 987), (7, 1234), (8, 8765), (9, 3456)]
Time: 0.000007 seconds

VI. Iter function and next function:
[1225, 4986, 6789, 7890, 2345, 6783, 987, 1234, 8765, 3456]
Time: 0.000022 seconds

VII. Map function:
[1225, 4986, 6789, 7890, 2345, 6783, 987, 1234, 8765, 3456]
Time: 0.000018 seconds

VIII. Using zip:
[(1225, 10), (4986, 20), (6789, 30), (7890, 40), (2345, 50), (6783, 60), (987, 70), (1234, 80), (8765, 90), (3456, 100)]
Time: 0.000009 seconds

IX. Using NumPy

**3)    For a List A, B, C, D, E write a python program to compute all the combinations and permutations**

In [33]:
from math import factorial
import timeit

# Define the list
elements = ['A', 'B', 'C', 'D', 'E']

# Function to compute all combinations
def compute_combinations(elements):
    def combinations(arr, n):
        if n == 0:
            return [[]]
        if not arr:
            return []
        return combinations(arr[1:], n) + [c + [arr[0]] for c in combinations(arr[1:], n - 1)]

    results = []
    for r in range(1, len(elements) + 1):
        results.extend(combinations(elements, r))
    return results

# Function to compute all permutations
def compute_permutations(elements):
    def permutations(arr):
        if len(arr) == 0:
            return [[]]
        return [p[:i] + [arr[0]] + p[i:] for i in range(len(arr)) for p in permutations(arr[1:])]

    return permutations(elements)

# Function to time an operation
def time_operation(func, *args, **kwargs):
    start_time = timeit.default_timer()
    result = func(*args, **kwargs)
    end_time = timeit.default_timer()
    elapsed = end_time - start_time
    return result, elapsed

# Main function to run the computations and profiling
def main():
    # Time combinations computation
    combinations, time_combinations = time_operation(compute_combinations, elements)
    print("Combinations:")
    for combo in combinations:
        print(combo)
    print(f"\nTime for combinations: {time_combinations:.6f} seconds")
    
    # Time permutations computation
    permutations, time_permutations = time_operation(compute_permutations, elements)
    print("\nPermutations:")
    for perm in permutations:
        print(perm)
    print(f"\nTime for permutations: {time_permutations:.6f} seconds")

if __name__ == "__main__":
    main()


Combinations:
['E']
['D']
['C']
['B']
['A']
['E', 'D']
['E', 'C']
['D', 'C']
['E', 'B']
['D', 'B']
['C', 'B']
['E', 'A']
['D', 'A']
['C', 'A']
['B', 'A']
['E', 'D', 'C']
['E', 'D', 'B']
['E', 'C', 'B']
['D', 'C', 'B']
['E', 'D', 'A']
['E', 'C', 'A']
['D', 'C', 'A']
['E', 'B', 'A']
['D', 'B', 'A']
['C', 'B', 'A']
['E', 'D', 'C', 'B']
['E', 'D', 'C', 'A']
['E', 'D', 'B', 'A']
['E', 'C', 'B', 'A']
['D', 'C', 'B', 'A']
['E', 'D', 'C', 'B', 'A']

Time for combinations: 0.000083 seconds

Permutations:
['A', 'B', 'C', 'D', 'E']
['A', 'B', 'C', 'E', 'D']
['A', 'B', 'D', 'C', 'E']
['A', 'B', 'E', 'C', 'D']
['A', 'B', 'D', 'E', 'C']
['A', 'B', 'E', 'D', 'C']
['A', 'C', 'B', 'D', 'E']
['A', 'C', 'B', 'E', 'D']
['A', 'D', 'B', 'C', 'E']
['A', 'E', 'B', 'C', 'D']
['A', 'D', 'B', 'E', 'C']
['A', 'E', 'B', 'D', 'C']
['A', 'C', 'D', 'B', 'E']
['A', 'C', 'E', 'B', 'D']
['A', 'D', 'C', 'B', 'E']
['A', 'E', 'C', 'B', 'D']
['A', 'D', 'E', 'B', 'C']
['A', 'E', 'D', 'B', 'C']
['A', 'C', 'D', 'E', 'B']
['A',

**4)    Using the same list use itertools compute permutations and combinations**

In [29]:
import itertools
import timeit

# Define the list
elements = ['A', 'B', 'C', 'D', 'E']

# Function to compute all combinations
def compute_combinations(elements):
    results = []
    for r in range(1, len(elements) + 1):
        results.extend(itertools.combinations(elements, r))
    return results

# Function to compute all permutations
def compute_permutations(elements):
    results = []
    for r in range(1, len(elements) + 1):
        results.extend(itertools.permutations(elements, r))
    return results

# Function to time an operation
def time_operation(func, *args, **kwargs):
    start_time = timeit.default_timer()
    result = func(*args, **kwargs)
    end_time = timeit.default_timer()
    elapsed = end_time - start_time
    return result, elapsed

# Main function to run the computations and timing
def main():
    # Time combinations computation
    combinations, time_combinations = time_operation(compute_combinations, elements)
    print("Combinations:")
    for combo in combinations:
        print(combo)
    print(f"\nTime for combinations: {time_combinations:.6f} seconds")
    
    # Time permutations computation
    permutations, time_permutations = time_operation(compute_permutations, elements)
    print("\nPermutations:")
    for perm in permutations:
        print(perm)
    print(f"\nTime for permutations: {time_permutations:.6f} seconds")

if __name__ == "__main__":
    main()


Combinations:
('A',)
('B',)
('C',)
('D',)
('E',)
('A', 'B')
('A', 'C')
('A', 'D')
('A', 'E')
('B', 'C')
('B', 'D')
('B', 'E')
('C', 'D')
('C', 'E')
('D', 'E')
('A', 'B', 'C')
('A', 'B', 'D')
('A', 'B', 'E')
('A', 'C', 'D')
('A', 'C', 'E')
('A', 'D', 'E')
('B', 'C', 'D')
('B', 'C', 'E')
('B', 'D', 'E')
('C', 'D', 'E')
('A', 'B', 'C', 'D')
('A', 'B', 'C', 'E')
('A', 'B', 'D', 'E')
('A', 'C', 'D', 'E')
('B', 'C', 'D', 'E')
('A', 'B', 'C', 'D', 'E')

Time for combinations: 0.003110 seconds

Permutations:
('A',)
('B',)
('C',)
('D',)
('E',)
('A', 'B')
('A', 'C')
('A', 'D')
('A', 'E')
('B', 'A')
('B', 'C')
('B', 'D')
('B', 'E')
('C', 'A')
('C', 'B')
('C', 'D')
('C', 'E')
('D', 'A')
('D', 'B')
('D', 'C')
('D', 'E')
('E', 'A')
('E', 'B')
('E', 'C')
('E', 'D')
('A', 'B', 'C')
('A', 'B', 'D')
('A', 'B', 'E')
('A', 'C', 'B')
('A', 'C', 'D')
('A', 'C', 'E')
('A', 'D', 'B')
('A', 'D', 'C')
('A', 'D', 'E')
('A', 'E', 'B')
('A', 'E', 'C')
('A', 'E', 'D')
('B', 'A', 'C')
('B', 'A', 'D')
('B', 'A', 'E')